export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const FETCH_TODOLIST = "POPULATE_TODOLIST";
export const SAVE_TODO_LIST = "SAVE_TODO_LIST";
export const POPULATE_FROM_IDB = "POPULATE_FROM_IDB";
