name: CI-Build

on: 
  pull_request:
    branches: 'master'

jobs:
  build:
    runs-on: [ubuntu-latest]
   
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v2
      with:
        node-version: 10.x

    - name: Running npm install...
      run: |
        npm install
    - name: Testing...
      run: |
        npm run test
    - name: Building...
      run: |
        npm run build --if-present
    - name: Notify failure via email
      if: failure()
      run: echo "FAILURE for PR check"
    - name: Notify success via email
      if: success()
      run: echo "SUCCESS test for PR from master"
    - name: Github context
      if: always()
      run: echo "${{ toJson(github) }}"