name: CI

on: 
  push:
    branches: 'uat'

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]

    strategy:
        node-version: 10.x
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ node-version }}

    - name: npm install...
      run: |
        npm install
    - name: npm test...
      run: |
        npm test
    - name: npm build...
      run: |
        npm build --if-present
    - name: send email>>
      run: echo "Email being sent...>>"
